/**
 * 	This files has the list of messages and other constants used across the application.
 */
var appMessages = {
		DELETE_CLIENT_TITLE: "Would you like to delete the Client?",
		DELETE_CLIENT_CONTENT: "All the details related to Client will be deleted!",
		DELETE_CLIENT_SUCCESS: "Client Deleted Successfully",
		DELETE_CLIENT_FAILURE: "Client could not be deleted, Please try again later.",
		CREATE_CLIENT_SUCCESS: "Client created successfully",
		CREATE_CLIENT_FAILURE: "Client could not be created at this moment. Please try again later.",
		UPDATE_CLIENT_SUCCESS: "Client details updated successfully",
		UPDATE_CLIENT_FALIURE: "Client details could not be updated at this moment. Please try again later.",
		DELETE_PROJECT_TITLE: "Would you like to delete the project?",
		DELETE_PROJECT_CONTENT: "All the details related to project will be deleted!",
		DELETE_PROJECT_SUCCESS: "Project Deleted Successfully",
		DELETE_PROJECT_FAILURE: "Project could not be deleted, Please try again later.",
		CREATE_PROJECT_SUCCESS: "Project created successfully",
		CREATE_PROJECT_FAILURE: "Project could not be created at this moment. Please try again later.",
		UPDATE_PROJECT_SUCCESS: "Project details updated successfully",
		UPDATE_PROJECT_FAILURE: "Project could not be created at this moment. Please try again later.",
		DELETE_RESOURCE_TITLE: "Would you like to delete the resource?",
		DELETE_RESOURCE_CONTENT: "All the details related to resource will be deleted!",
		DELETE_RESOURCE_SUCCESS: "Resource Deleted Successfully",
		DELETE_RESOURCE_FAILURE: "Resource could not be deleted, Please try again later.",
		CREATE_RESOURCE_SUCCESS: "Resource created successfully",
		CREATE_RESOURCE_FAILURE: "Resource could not be created at this moment. Please try again later.",
		UPDATE_RESOURCE_SUCCESS: "Resource details updated successfully",
		UPDATE_RESOURCE_FAILURE: "Resource could not be updated at this moment. Please try again later.",
		MAP_RESOURCE_SUCCESS: "Resource Allocated Successfully",
		MAP_RESOURCE_FAILURE: "Resource could not be allocated at this moment. Please try again later.",
		UNMAP_RESOURCE_SUCCESS: "Resource Released Successfully",
		UNMAP_RESOURCE_FAILURE: "Resource could not be released, Please try again later.",
		UPDATE_RESOURCE_MAP_SUCCESS: "Resource Allocation Updated Successfully",
		UPDATE_RESOURCE_MAP_FAILURE: "Resource allocation could not be updated at this moment. Please try again later.",
		UNMAP_RESOURCE_TEMPLATE: "<h4>Would you like to unallocate the resource from project? <br/><br/> Please ensure the resource has filled the timesheet!</h4>",
		CREATE_TASK_SUCCESS: "Task created successfully",
		CREATE_TASK_FAILURE: "Task could not be created at this moment. Please try again later.",
		UPDATE_TASK_SUCCESS: "Task updated successfully",
		UPDATE_TASK_FAILURE: "Task could not be updated at this moment. Please try again later.",
		DELETE_TASK_TITLE: "Would you like to delete the task?",
		DELETE_TASK_CONTENT: "All the details related to task will be deleted!",
		DELETE_TASK_SUCCESS: "Task Deleted Successfully",
		DELETE_TASK_FAILURE: "Task could not be deleted, Please try again later",
		UPDATE_PASSWORD_SUCCESS: "Password changed successfully",
		RELOGIN_AFTER_RESET: "Password changed successfully. Please login with your new password to continue.",
		UPDATE_PASSWORD_FAILURE: "Password could not be changed at this moment. Please try again later.",
		SELECT_USERS_TO_APPROVE: "Please select the users before approving",
		NO_SUBMITTED_ENTRIES_TO_APPROVE: "There are no submitted hours in the selected week",
		APPROVE_CONFIRMATION_TITLE: "Do you want to approve the entered hours?",
		APPROVE_CONFIRMATION_CONTENT: "Only the submitted records will be approved.",
		APPROVE_SUCCESS: "Timesheet approved successfully",
		APPROVE_FAILURE: "Timesheet could not be approved at this moment, Please try again later.",
		SELECT_USERS_TO_REJECT: "Please select the users before rejecting",
		REJECT_CONFIRMATION_TITLE: "Do you want to reject the entered hours?",
		REJECT_CONFIRMATION_CONTENT: "Only the submitted records will be rejected.",
		REJECT_SUCCESS: "Timesheet rejected successfully",
		REJECT_FAILURE: "Timesheet could not be rejected at this moment, Please try again later.",
		ENTER_PREVIOUS_DAYS: "Enter time for all previous days.",
		MIN_HOURS: "Hours must be a number more than 0",
		EFFORTS_EXCEEDING: "Effort exceeding the number of remaining hours. Please contact your manager.",
		MAX_HOURS_PER_DAY: "Total Hours Exceeds 24hrs",
		TOTAL_HOURS_WARN: "Please fill 8 hours before saving or submitting.",
		ENTER_BEFORE_SUBMIT: "Please Enter Hours to Submit",
		ENTER_BEFORE_SAVE: "Please Enter Hours to Save",
		TIMESHEET_UPDATE_SUCCESS: "Timesheet Updated Successfully",
		TIMESHEET_SAVE_SUCCESS: "Timesheet Saved Successfully",
		TIMESHEET_SAVE_FAILURE: "Timesheet could not be saved at this moment, Please try again later.",
		TIMESHEET_SUBMIT_SUCCESS: "Timesheet Submitted Successfully",
		TIMESHEET_SUBMIT_FAILURE: "Timesheet could not be submitted at this moment, Please try again later.",
		TIMESHEET_EDIT_CANCEL_TITLE: "Would you like to cancel editing?",
		TIMESHEET_EDIT_CANCEL_CONTENT: "All the changes made for the selected resource will be discarded!",
		INVALID_USER_LOGIN: "Invalid User. Please Verify!!",
		PASSWORD_RESET_SUCCESS: "Password has been reset and sent to your registered email.",
		PASSWORD_RESET_FAILURE: "Password could not be reset at this moment. Please try again later.",
		HOURS_VALIDATION: "Hours can have upto 2 decimal points.",
		CANNOT_DELETE_ADMIN: "You are not allowed to delete the admin",
		HOLIDAY_HOURS_CONFIRMATION_TITLE: "You are entering hours for a non-working day.",
		HOLIDAY_HOURS_CONFIRMATION_CONTENT: "Are you sure?",
		FETCH_HOLIDAY_ERROR: "Holiday list could not be fetched at this moment. Please try again later.",
		CANCEL_MARK_HOLIDAY_TITLE: "Do you want to ignore the changes made?",
		CANCEL_MARK_HOLIDAY_CONTENT: "All the changes made will be lost. Do you want to cancel editing?",
		UPDATE_HOLIDAY_SUCCESS: "Holiday list updated successfully",
		UPDATE_HOLIDAY_FAILURE: "Holiday list could not be updated. Please try again later",
		UPDATE_EMP_ID_CONFIRM: "You are changing the employee id.",
		SUBMIT_CONFIRMATION_TITLE: "You are about to submit the hours, Are you sure?",
		SUBMIT_CONFIRMATION_CONTENT: "You will not be able to edit the hours once submitted.",
		TIMESHEET_DELETE_CONFIRM_TITLE: "You are about to delete entries, Are you sure?",
		TIMESHEET_DELETE_CONFIRM_CONTENT: "Submitted or Approved hours will not be deleted.",
		TIMESHEET_DELETE_SUCCESS: "Entries deleted successfully.",
		TIMESHEET_DELETE_FAILURE: "Entries could not be deleted at this moment. Please try again later.",
		NO_SAVED_ENTRIES_TO_DELETE: "There are no hours to delete."
};

var appConstants = {
	billingTypes: [ "Fixed", "Time & Material", "Dedicated", "Milestone Billing", "Non Billable"],
	skills: ["Admin","Angular","AS/400","Business Analysis","Cloud","CRM","CSS","Database Specialist","Finance","HR","HTML","IT Support","Javascript","J2EE","Mobility",".Net","Others","PHP","Project Management","Python","Sales/Marketing","Testing","UX Designer"],
	us_states: ["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina"," North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"],
	country_usa: "United States of America (USA)",
	jira_instructions: [
		"Import File should be in Excel(.xls,.xslx) format.",
		"The contents should be as per the Template attached (downloadable).",
		"The Project Id should be same both in the File and Orion. Import Separate File for every Project.",
		"There should be only one entry for a resource for a given task in a day.",
		"The total hours spent by all the resources for a given task cannot exceed the estimated hours. Since Jira allows the user to enter more hours than estimated, Orion will show the exceeded hours as a Negative number.",
		"Any errors encountered during the Import process will be shown in the Remarks column against that entry. You can view the errors in the same file.",
		"To ensure Data Integrity, please avoid multiple Imports.",
		"If any field is empty, that needs to be populated with a default value before upload."
	],
	purge_instructions: [
		'All the legacy data beyond {{date}} will be deleted from database',
		'It includes timesheet entries, projects, tasks and resources'
	]
}